# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="gitfs"
REALVERSION="0.4.5.1"
#REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SRC_URI="https://github.com/PressLabs/${REALNAME}/archive/${REALVERSION}.tar.gz"
SOURCEFILE="${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python2_7 python3_4 python3_5 python3_6 )

inherit gs-pypi

DESCRIPTION="Version controlled file system."

HOMEPAGE="http://www.presslabs.com/gitfs/"
LICENSE=""

SLOT="0"
KEYWORDS="~amd64 ~x86"

